---
- name: Run the client container
  docker_container:
    name: client
    image: amuturia/client:v0.0.1
    ports:
      - "3000:3000"
    restart_policy: always
    networks:
      - name: bridge
    depends_on:
      - backend
