services:
  

  #The database that will be assosiated with the website
  mongo:
    container_name: db
    image: mongo:4.0-xenial
    restart: always
    ports:
      - 27017:27017 
    volumes:
      - yolomy:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

#Declare the volume that the database will be using to persiste the data
volumes:
  yolomy: 
    driver: local