services:
  #Build the client container for the website
  client: 
    container_name: client
    image: amuturia/client:v0.0.1
    build:
      context: ./client
      dockerfile: client.dockerfile
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - backend

  #Build the backend container for my website
  backend: 
    container_name: backend
    image: amuturia/backend:v0.0.1
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - 5000:5000
    environment:
      - DB_URL=mongodb://mongo/yolomy


  #The database that will be assosiated with the website
  mongo:
    container_name: db
    image: mongo:4.0-xenial
    restart: always
    ports:
      - 27017:27017 
    volumes:
      - yolomy:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example

#Declare the volume that the database will be using to persiste the data
volumes:
  yolomy: 
    driver: local