- name: Install MongoDB
  apt:
    name: mongodb
    state: present

- name: Ensure MongoDB is running
  service:
    name: mongodb
    state: started
    enabled: true

- name: Create MongoDB database
  command: mongo --eval "use {{ mongo_db_name }}"