- hosts: all  
  become: true
  roles:

    - testcon
    - check_update 
    - mongo

  tasks:

    - name: Docker Compose
      apt:
        name: docker-compose
        state: latest

    - name: Copy docker-compose.yml to the Vagrant machine
      copy:
        src: docker-compose.yml
        dest: /home/vagrant/docker-compose.yml

    - name: Run Docker Compose
      command: docker-compose up -d
      args:
        chdir: /home/vagrant